---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9093
  name: server
  clusterIP: None
  selector:
    app: kafka
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv
  namespace: kafka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka_data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-pv-claim
  namespace: kafka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
  namespace: kakfa
data:
  advertised.listeners: 'PLAINTEXT://kafka-0.kafka-svc.kafka.svc.cluster.local:9093'
  connect: 'zk-0.zk-svc.kakfa.svc.cluster.local:2182'
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kakfa
spec:
  serviceName: kafka-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - kafka
            topologyKey: kubernetes.io/hostname
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
  podAffinityTerm:
    labelSelector:
      matchExpressions:
        - key: app
          operator: In
          values:
            - zk
    topologyKey: kubernetes.io/hostname
  terminationGracePeriodSeconds: 300
  volumes:
    - name: kafka-pv-storage
  persistentVolumeClaim:
    claimName: kafka-pv-claim
  containers:
    - name: k8skafka
  imagePullPolicy: Always
  image: 'confluentinc/cp-kafka:latest'
  resources: 
    requests: 
      memory: 1Gi
      cpu: 500m
  ports:
    - containerPort: 9093
  name: server
  command:
    - sh
    - '-c'
    - >-
      KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-${HOSTNAME##*-}.kafka-svc.kakfa.svc.cluster.local:9093
      KAFKA_BROKER_ID=${HOSTNAME##*-} /etc/confluent/docker/run
  env:
    - name: KAFKA_HEAP_OPTS
      value: '-Xmx512M -Xms512M'
    - name: KAFKA_OPTS
      value: '-Dlogging.level=INFO'
    - name: KAFKA_ADVERTISED_LISTENERS
      valueFrom:
        configMapKeyRef:
          name: kafka-cm
          key: advertised.listeners
    - name: KAFKA_ZOOKEEPER_CONNECT
      valueFrom:
        configMapKeyRef:
          name: kafka-cm
          key: connect
  volumeMounts:
    - name: kafka-pv-storage
  mountPath: /var/lib/kafka
