---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  namespace: kafka
  labels:
    app: zk-svc
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zoo-pv
  namespace: kakfa
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/zoo_data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zoo-pv-claim
  namespace: kafka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-cm
  namespace: kakfa
data:
  tick: '2000'
  servers: 'zk-0.zk-svc.kakfa.svc.cluster.local:2888:3888'
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
  namespace: kakfa
spec:
  serviceName: zk-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: zk
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zk
      topologyKey: kubernetes.io/hostname
  volumes:
    - name: zoo-pv-storage
  persistentVolumeClaim:
    claimName: zoo-pv-claim
  containers:
    - name: k8szk
  imagePullPolicy: Always
  image: 'confluentinc/cp-zookeeper:latest'
  command:
    - bash
    - '-c'
    - 'ZOOKEEPER_SERVER_ID=$((${HOSTNAME:3}+1)) && /etc/confluent/docker/run'
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
  ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: server
    - containerPort: 3888
      name: leader-election
  env:
    - name: ZOOKEEPER_TICK_TIME
      valueFrom:
        configMapKeyRef:
          name: zk-cm
          key: tick
    - name: ZOOKEEPER_SYNC_LIMIT
      valueFrom:
        configMapKeyRef:
          name: zk-cm
          key: tick
    - name: ZOOKEEPER_SERVERS
      valueFrom:
        configMapKeyRef:
          name: zk-cm
          key: servers
    - name: ZOOKEEPER_CLIENT_PORT
      value: '2182'
    - name: ZOOKEEPER_SERVER_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  volumeMounts:
    - name: zoo-pv-storage
  mountPath: /var/lib/zookeeper
