apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: test
  spec: null
  terminationGracePeriodSeconds: 10
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
        claimName: mongo-pv-claim
  containers:
    - name: mongo
      image: mongo
      command:
        - mongod
        - '--bind_ip'
        - 0.0.0.0
        - '--smallfiles'
        - '--noprealloc'
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
    